export const SALES_LOAD_MENU = 'SALES_LOAD_MENU';
export const SALES_SET_MENU = 'SALES_SET_MENU';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';
export const SALES_SET_HEADERNAME = 'SALES_SET_HEADERNAME';
export const SALES_SET_SIZE = 'SALES_SET_SIZE';
export const SALES_ADD_TRANSITEM = 'SALES_ADD_TRANSITEM';
export const SALES_ADD_TRANSITEM_ONEPARM = 'SALES_ADD_TRANSITEM_ONEPARM';
export const SALES_CHANGE_TRANSITEM = 'SALES_CHANGE_TRANSITEM';
export const SALES_CLEAR_TRANSACTION = 'SALES_CLEAR_TRANSACTION';
export const SALES_TRANSACTION_POST_OK = 'SALES_TRANSACTION_POST_OK';
export const FETCH_TRANSACTION_POST_FAILED = 'FETCH_TRANSACTION_POST_FAILED';
export const SALES_SET_CUSTOMERNAME = 'SALES_SET_CUSTOMERNAME';
export const SALES_CLEARMODALMESSAGE = 'SALES_CLEARMODALMESSAGE';


